### ISSUE TITLE
Traefik configuration wrong

### ISSUE THREAD

**Issue by silardsimon** [paidem/guacozy#34]
Hi,

I tried deploying this today, the configuration from [the readme](https://guacozy.readthedocs.io/en/latest/installation/traefik/#working-example) for Traefik is quite wrong. Here's a working config, for reference:

```
version: '3'

services:
  server:
    container_name: guac_server
    image: guacozy/guacozy-server
    restart: always
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
      - FIELD_ENCRYPTION_KEY=qjq4ObsXMqiqQyfKgD-jjEGm4ep8RaHKGRg4ohGCi1A=
      - DJANGO_DB_URL=postgres://postgres@db:5432/postgres
      - DJANGO_ALLOWED_HOSTS=*
    ports:
      - 10080:80
      - 10443:443
    labels:
      - traefik.web.port=80
      - traefik.enable=true
      - traefik.web.frontend.rule=Host:guacozy.example.com
      - traefik.docker.network=traefik
  guacd:
    image: linuxserver/guacd
    restart: always
    container_name: guacd
  db:
    container_name: guacdb
    image: postgres:10.4-alpine
    restart: always
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    external:
      name: webproxy
```
